#!/usr/bin/env bash
# Displays information about subdomains of a domain
# shellcheck disable=SC2086
my_function () {
	echo -n "The subdomain $2 is a "
	dig "$2"."$1" | grep -A1 'ANSWER SECTION:'| tail -1 | awk '{ printf "%s record and points to %s\n", $4, $5 }'
}

if [ $# -ne 2 ]; then
	for sub in 'www' 'lb-01' 'web-01' 'web-02' ; do
		my_function $1 $sub
	done
else
		my_function $1 $2
fi
