#!/usr/bin/env bash
sudo systemctl start mysql.service
echo "CREATE USER IF NOT EXISTS 'holberton_user'@'localhost'IDENTIFIED BY 'projectcorrection280hbtn';
GRANT ALL PRIVILEGES ON *.* TO 'holberton_user'@'localhost';" | sudo mysql
