#!/usr/bin/env bash

echo "CREATE DATABASE IF NOT EXISTS \`tyrell_corp\`;
use tyrell_corp;
CREATE TABLE IF NOT EXISTS \`nexus6\`(\`id\` INT, \`name\` VARCHAR(256));
INSERT INTO \`nexus6\` (\`id\`, \`name\`) VALUES (09, \"test 1\");
SELECT * from \`nexus6\`; 
CREATE USER IF NOT EXISTS 'holberton_user'@'localhost'IDENTIFIED BY 'projectcorrection280hbtn';
GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost' ;
GRANT SELECT ON 'mysql.user' TO 'holberton_user'@'localhost';
FLUSH PRIVILEGES;
"| sudo mysql
